[package]
name = "shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.33"
exacl = "0.12.0"
list = "0.1.3"
users = "0.11.0"
xattr = "1.3.1"
